// Pushes ONLY the geocoded coordinates from the seed files into rows that
// already exist: state-guide places, itinerary day stops, and country-guide
// reference cities. Run it after either geocoding script.
//
//   npm run seed:coords
//
// `npm run seed` would also do this, but it deletes and recreates every state
// guide to get there — and a mid-run connection drop then leaves production
// with no state guides at all until a rerun completes (this has happened twice;
// see CLAUDE.md, "Incident: npm run seed is not actually crash-safe"). Writing
// two columns on rows that already exist is a far smaller thing to do, and
// it's what you want after re-running scripts/geocode_places.py.
//
// Matched on (state slug, place name) because StatePlace ids are cuids
// regenerated on every full reseed and so aren't stable across runs.
import { PrismaClient } from "@prisma/client";
import stateGuidesSeed from "../data/state-guides-seed.json";
import itinerariesSeed from "../data/itineraries-seed.json";
import countryFactsSeed from "../data/country-facts-seed.json";

const prisma = new PrismaClient();

async function main() {
  const states = stateGuidesSeed as any[];
  let updated = 0;
  let cleared = 0;
  let missing = 0;

  for (const state of states) {
    const guide = await prisma.stateGuide.findUnique({
      where: { slug: state.slug },
      include: { places: { select: { id: true, name: true } } },
    });
    if (!guide) {
      console.warn(`  ! no state guide in the database for ${state.slug} — skipping`);
      continue;
    }

    const byName = new Map(guide.places.map((p) => [p.name, p.id]));

    for (const place of state.places) {
      const id = byName.get(place.name);
      if (!id) {
        missing += 1;
        continue;
      }
      const lat = place.latitude ?? null;
      const lon = place.longitude ?? null;
      await prisma.statePlace.update({
        where: { id },
        data: { latitude: lat, longitude: lon },
      });
      if (lat === null) cleared += 1;
      else updated += 1;
    }
  }

  const withCoords = await prisma.statePlace.count({ where: { latitude: { not: null } } });
  const total = await prisma.statePlace.count();
  console.log(
    `\nState places: ${updated} given coordinates, ${cleared} left without ` +
      `(unresolved, or food/culture entries that have no location)` +
      (missing > 0 ? `, ${missing} in the seed file had no matching row` : "") +
      `.\n  Database now has ${withCoords} of ${total} places mapped.`
  );

  // --- Itinerary day stops -------------------------------------------------
  // Matched on (itinerary title, dayNumber): ItineraryDay ids are cuids
  // regenerated by every full reseed, so they aren't stable to match on.
  let dayUpdated = 0;
  let dayCleared = 0;
  for (const it of itinerariesSeed as any[]) {
    const row = await prisma.itinerary.findFirst({
      where: { title: it.title },
      include: { days: { select: { id: true, dayNumber: true } } },
    });
    if (!row) continue;
    const byDayNumber = new Map(row.days.map((d) => [d.dayNumber, d.id]));
    for (const day of it.days ?? []) {
      const id = byDayNumber.get(day.day_number);
      if (!id) continue;
      const lat = day.latitude ?? null;
      const lon = day.longitude ?? null;
      await prisma.itineraryDay.update({
        where: { id },
        data: { latitude: lat, longitude: lon },
      });
      if (lat === null) dayCleared += 1;
      else dayUpdated += 1;
    }
  }
  const daysMapped = await prisma.itineraryDay.count({ where: { latitude: { not: null } } });
  const daysTotal = await prisma.itineraryDay.count();
  console.log(
    `\nItinerary days: ${dayUpdated} given coordinates, ${dayCleared} left without ` +
      `(rest days, travel days, and stops that couldn't be placed).` +
      `\n  Database now has ${daysMapped} of ${daysTotal} days mapped.`
  );

  // --- Country reference cities --------------------------------------------
  let countryUpdated = 0;
  for (const c of countryFactsSeed as any[]) {
    if (c.latitude === undefined) continue;
    const res = await prisma.countryFact.updateMany({
      where: { country: c.country },
      data: { latitude: c.latitude ?? null, longitude: c.longitude ?? null },
    });
    if (res.count > 0 && c.latitude !== null) countryUpdated += 1;
  }
  console.log(`\nCountry guides: ${countryUpdated} given reference-city coordinates.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
