// Seeds ONLY the road-eats tables, and links itinerary days to their eat town.
//
//   npm run seed:eats
//
// The destructive full `npm run seed` would also do this, but it deletes and
// recreates every itinerary to get there, and a mid-run connection drop leaves
// production without itineraries until a rerun completes (see CLAUDE.md,
// "Incident: npm run seed is not actually crash-safe"). Road eats get added a
// state at a time and re-verified periodically, so they need a path that never
// touches anything else.
//
// Each region is removed and recreated in one transaction, so a failure part-way
// leaves the previous version of that region intact rather than half-written.
import { PrismaClient } from "@prisma/client";
import roadEatsSeed from "../data/road-eats-seed.json";
import itinerariesSeed from "../data/itineraries-seed.json";

const prisma = new PrismaClient();

async function main() {
  const regions = roadEatsSeed as any[];

  let stops = 0;
  let eats = 0;
  for (const r of regions) {
    await prisma.$transaction([
      prisma.roadEatStop.deleteMany({ where: { regionKey: r.region_key } }),
      ...r.stops.map((s: any) =>
        prisma.roadEatStop.create({
          data: {
            regionKey: r.region_key,
            town: s.town,
            note: s.note ?? null,
            noteSourceUrl: s.note_source_url ?? null,
            lastVerifiedDate: new Date(r.last_verified_date),
            eats: {
              create: s.eats.map((e: any, i: number) => ({
                name: e.name,
                kind: e.kind,
                meal: e.meal,
                whatToOrder: e.what_to_order,
                why: e.why,
                priceTier: e.price_tier ?? null,
                hoursNote: e.hours_note ?? null,
                openEvidence: e.open_evidence,
                sourceUrl: e.source_url,
                sourceName: e.source_name,
                sortOrder: i,
              })),
            },
          },
        })
      ),
    ]);
    stops += r.stops.length;
    eats += r.stops.reduce((n: number, s: any) => n + s.eats.length, 0);
    console.log(`  seeded ${r.region_key}: ${r.stops.length} stops`);
  }

  // Link itinerary days to their eat town. Matched on (title, dayNumber) because
  // ItineraryDay ids are cuids regenerated by every full reseed.
  let linked = 0;
  for (const it of itinerariesSeed as any[]) {
    const row = await prisma.itinerary.findFirst({
      where: { title: it.title },
      include: { days: { select: { id: true, dayNumber: true } } },
    });
    if (!row) continue;
    const byDay = new Map(row.days.map((d) => [d.dayNumber, d.id]));
    for (const day of it.days ?? []) {
      if (day.eat_town === undefined) continue;
      const id = byDay.get(day.day_number);
      if (!id) continue;
      await prisma.itineraryDay.update({ where: { id }, data: { eatTown: day.eat_town ?? null } });
      if (day.eat_town) linked += 1;
    }
  }

  const dbStops = await prisma.roadEatStop.count();
  const dbEats = await prisma.roadEat.count();
  console.log(
    `\n${regions.length} region(s): ${stops} stops, ${eats} eats seeded; ${linked} itinerary days linked to a town.` +
      `\nDatabase now has ${dbStops} stops and ${dbEats} eats.`
  );
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
